### ISSUE TITLE
Negative trs in launchLocomotion.ini

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-configuration-files#11]
Negative `trs` in `launchLocomotion.ini`: https://github.com/roboticslab-uc3m/teo-configuration-files/blob/b37b041ddcfddfe1347cfb4d5c22737d0aa069d2/share/launchLocomotion/conf/launchLocomotion.ini

I guess this means we should update the diagram (and kinematics later on).

**Comment by rsantos88** [comment]
The justification is that they are only `-1` for `CuiAbsolute`, never for motors.
