### ISSUE TITLE
Adding Mass CoG and intertia to the .ini files

### ISSUE THREAD

**Issue by AlvaroMartinezR** [roboticslab-uc3m/teo-configuration-files#15]
As @jmgarciah noted, the .ini files of the legs lack the dynamic information that the arms have. However, this information is useless and wrong, i.e.
 ``link_1 (offset -90.0) (D 0.0 ) (A 0.0 ) (alpha 90.0) (mass 0 ) (cog 0 0 0) (inertia 0 0 0)``

So I will update all files with the information found [here](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/7d7f7216ecc2e558c65314d4862a3c90cc10a625/appendix/b-teo-dynamic-information.md)

**Comment by jgvictores** [comment]
The current values are approximations, good enough for having enabled gravity compensation.

Improvements, as always, are welcome. :smile:

**Comment by AlvaroMartinezR** [comment]
Done

**Comment by jgvictores** [comment]
https://github.com/roboticslab-uc3m/teo-configuration-files/commit/f355beb437221ec9afb9a12dfcacd2b3b06cca6b

**Comment by jgvictores** [comment]
Reopening until tested, ok?

**Comment by AlvaroMartinezR** [comment]
@rsantos88 and I tested this new values. The results for gcmp in  the arms were very satisfactory. However, the legs have several complications:

- Sometimes a joint is blocked and cannot be moved, e.g. the ankle, both sagittal and frontal.
- FrontalHip does not control at all, possible the weight assigned is too low or the motor does not provide enough torque.

**Comment by jgvictores** [comment]
Related to https://github.com/roboticslab-uc3m/teo-main/issues/16

**Comment by jgvictores** [comment]
Closing as https://github.com/roboticslab-uc3m/teo-configuration-files/commit/f355beb437221ec9afb9a12dfcacd2b3b06cca6b has been merged to `develop` and  https://github.com/roboticslab-uc3m/teo-configuration-files/issues/15#issuecomment-405189986 stated it has been tested.

**Comment by PeterBowman** [comment]
> Closing as [f355beb](https://github.com/roboticslab-uc3m/teo-configuration-files/commit/f355beb437221ec9afb9a12dfcacd2b3b06cca6b) has been merged to `develop` and [#15 (comment)](https://github.com/roboticslab-uc3m/teo-configuration-files/issues/15#issuecomment-405189986) stated it has been tested.

@jgvictores that commit was reverted shortly thereafter (https://github.com/roboticslab-uc3m/teo-configuration-files/commit/ed94eaecbea1bee7af357d660f0b17e3a91ca889) and never brought back to develop again, so it is kinda lost in the commit history, now. Shall I undo the rollback?

BTW the left arm .ini was tested by yourself on this Monday (lecture in lab).

**Comment by PeterBowman** [comment]
We'll start from scratch at https://github.com/roboticslab-uc3m/teo-main/issues/16.
