### ISSUE TITLE
Include motor constants in launchLocomotion.ini

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-configuration-files#23]
`ks` are currently missing: [ref](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/d588723e02bb340766bb15b31f32eb2f2da0ccc7/share/launchLocomotion/conf/launchLocomotion.ini) (cf. [launchManipulation.ini](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/d588723e02bb340766bb15b31f32eb2f2da0ccc7/share/launchManipulation/conf/launchManipulation.ini#L13)). Check motors in [teo-developer-manual](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/5b9f6ac3e53ef8b39ae3bd45f9847c89ccca899e/csv/motores-motores.csv) and [maxongroup.com](https://www.maxongroup.com/maxon/view/product/339282) (*Specifications* > *Torque constant* > convert to Nm/A).

**Comment by PeterBowman** [comment]
| Motor reference ID | CAN nodes (right leg) | CAN nodes (left leg) | Motor constant (Nm/A) |
| ----------- | --- | --- | --- |
| [251601](https://www.maxongroup.com/maxon/view/product/251601) | 1, 5, 14 | 12, 13 | 0.0335 |
| [402686](https://www.maxongroup.com/maxon/view/product/402686) | 2, 3, 4 | 9, 10, 11 | 0.0533 |
| [339287](https://www.maxongroup.com/maxon/view/product/339287) | 6 | 7, 8 | 0.101 |

**Comment by jgvictores** [comment]
@PeterBowman Thanks a lot for this!!

**Comment by PeterBowman** [comment]
> @PeterBowman Thanks a lot for this!!

I'm sorry, but this table is utterly wrong. Don't even look at [motores-motores.csv](https://github.com/roboticslab-uc3m/teo-developer-manual/blob/5b9f6ac3e53ef8b39ae3bd45f9847c89ccca899e/csv/motores-motores.csv). I'm so frustrated, not a single piece of info can be trusted here.

**Comment by jgvictores** [comment]
Sorry, pity...

I guess for now it's just okay to see Joint names (very first column at https://github.com/roboticslab-uc3m/teo-developer-manual/blob/804582e3af4a31fc616a10ea6287ddc43d263279/csv/motores-motores.csv), maybe first six columns except for 3rd affected by https://github.com/roboticslab-uc3m/teo-developer-manual/issues/66
