### ISSUE TITLE
Regression on how we use yarpscope due to MAS

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-configuration-files#27]
In the following lines we use `yarpscope` to see `analogSensor` data:
https://github.com/roboticslab-uc3m/teo-configuration-files/blob/20928f1372856a6f6803d79d708c60a9d4d0e9a4/share/applications/yarpmanager/teoTools.xml#L44-L79

This is no longer compatible with the newer MAS output. Example from 2 force/torque sensors: `() () () () () (((-8.26166901926451e-28 -8.65001222429981e-26 8.43028247603727e-26 4.19666601412255e-26 -1.49782273589117e-27 -5.4792163828055e-28) 0.0) ((-1.18296526701132e-27 -9.15613906203435e-26 -9.26964896060886e-26 4.32168175222268e-26 2.42084410323602e-27 -5.89853799337956e-28) 0.0)) () () ()`

Note: solution should extend to `teoSimTools.xml`

**Comment by jgvictores** [comment]
Compatibility is achieved via newly developed [BottleExtract](https://github.com/roboticslab-uc3m/yarp-devices/blob/e3b9d8e0874c75d26a1b0e05d9d63bcf805aff76/libraries/YarpPlugins/PortMonitorPlugins/cpp/bottle_extract_portmonitor/BottleExtract.cpp) YARP portmonitor.

An example of use with `teoSim` can be seen at: https://github.com/roboticslab-uc3m/teo-configuration-files/blob/7c3a88329cdde9dac196e692368b445fa83a2545/share/applications/teoSimTools.xml#L17-L40

Added note for real robot at https://github.com/roboticslab-uc3m/yarp-devices/issues/240. Closing issue! :tada:

**Comment by PeterBowman** [comment]
If I understand correctly, a similar solution is going upstream at https://github.com/robotology/yarp/pull/2610 (which basically is a follow-up to your comment at https://github.com/robotology/yarp/issues/1693#issuecomment-574683563, @jgvictores).

Edit: the patch has been merged and is targeted for the YARP 3.6.0 release (probably happening tomorrow).

**Comment by jgvictores** [comment]
It seems it could be fit for the specific task! Still, `BottleExtract` is currently more flexible, and I additionally think the refactorization proposed at point 2 of https://github.com/robotology/yarp/issues/1693#issuecomment-574683563 still makes sense. But have to look into it, anyway. : )
