### ISSUE TITLE
[teoBase app] and [teoSim app] use absolute paths for kinematics

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-configuration-files#3]
_From @jgvictores on October 12, 2016 15:6_

[teoBase app] and [teoSim app] use absolute paths for kinematics. Should use relative, e.g. with ResourceFinder.

_Copied from original issue: roboticslab-uc3m/kinematics-dynamics#62_

**Comment by jgvictores** [comment]
_From @PeterBowman on October 16, 2017 11:56_

The initialization part was handled at 33c4b42 on the `KdlSolver` plugin. Now, we may consider updating relevant XMLs at teo-configuration-files:

* [teoBase.xml](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/e52590665a54cfbf33863f6e6264bdcc1df154a1/share/teoBase/scripts/teoBase.xml)
* [teoSimBase.xml](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/e52590665a54cfbf33863f6e6264bdcc1df154a1/share/teoSimBase/scripts/teoSimBase.xml)

@jgvictores could you take a look at this (move/close)?

**Comment by PeterBowman** [comment]
Can be solved right away if we just do `--from fixedTrunk-leftArm-kinematics.ini --context kinematics` or similar. On a broader perspective, this issue could be regarded as a subtask of https://github.com/roboticslab-uc3m/questions-and-answers/issues/61.

**Comment by PeterBowman** [comment]
Done at https://github.com/roboticslab-uc3m/teo-configuration-files/commit/a89480fa727433826e875cd606c843586cacb4a7.
