### ISSUE TITLE
Review and clean share/kinematics

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-configuration-files#7]
Review `share/kinematics`. There are [currently](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/32191f5e0e4ccd08afcb30c6f41e162fab977320/share/kinematics) more files than limbs:
1. Some may be required.
1. Some may be redundant.
1. Some may mean we need to add features to https://github.com/roboticslab-uc3m/kinematics-dynamics

**Comment by jgvictores** [comment]
Blocked by https://github.com/roboticslab-uc3m/teo-main/issues/38

**Comment by rsantos88** [comment]
Regarding to PR https://github.com/roboticslab-uc3m/teo-configuration-files/pull/20
Some questions:
* I've added the links of the arms+fetch in [rightArmKinematics-fetch.ini](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/test-update-kinematic/share/kinematics/rightArmKinematics-fetch.ini) and [leftArmKinematics-fetch.ini](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/test-update-kinematic/share/kinematics/leftArmKinematics-fetch.ini) but I understand that it would be necessary to separate the masses of the arm and the fetch. 
Are these data documented?
* Can I delete these files?: 
  - leftArm3dofKinematics.ini 
  - leftArm22Kinematics.ini
  - leftArmKinematics-isolated.ini
  - rightArmKinematics-isolated.ini
  - rightArmKinematics-pan45.ini
  - rightArmKinematics-pan45-tilt30.ini
  - trunkKinematics.ini

**Comment by jgvictores** [comment]
> Can I delete these files?:
> * leftArm3dofKinematics.ini
> * leftArm22Kinematics.ini
> * leftArmKinematics-isolated.ini
> * rightArmKinematics-isolated.ini
> * rightArmKinematics-pan45.ini
> * rightArmKinematics-pan45-tilt30.ini
> * trunkKinematics.ini

Essentially, yes. 1. Let's keep track of changes at the PR (https://github.com/roboticslab-uc3m/teo-configuration-files/pull/21)

**Comment by jgvictores** [comment]
Done by @rsantos88 at https://github.com/roboticslab-uc3m/teo-configuration-files/pull/21
